main_page:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    defaults:
        _locale: ru
    requirements:
        _locale: '%app.locales%'

admin_categories:
    resource: App\Controller\Admin\CategoriesController
    prefix: /admin/categories

admin_posts:
    resource: App\Controller\Admin\PostsController
    prefix: /admin/posts